import type { Metadata } from "next";
import "./globals.css";
import { TimerProvider } from "./context/TimerContext";

export const metadata: Metadata = {
  title: "Hackaton-IA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TimerProvider>
          {children}
        </TimerProvider>
      </body>
    </html>
  );
}
